<a href="https://colab.research.google.com/github/mirajsankdecha/python/blob/main/Unit_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print(array1)

[1 2 3 4 5]


In [ ]:
list2 = [6,7,8,9,10]
array2 = np.array(list2)
print(array2)

[ 6  7  8  9 10]


In [ ]:
array3 = np.zeros(4)
print(array3)

In [ ]:
array4 = np.arange(10)
print(array4)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
array5 = np.arange(1,9,2)
print(array5)

[1 3 5 7]


In [ ]:
array6 = np.floor(np.random.rand(5) * 10)
print(array6)

[0. 3. 0. 2. 6.]


In [ ]:
array7 = np.empty(4)
print(array7)

[4.75194631e-310 0.00000000e+000 7.42861821e-091 9.15508060e-071]


In [ ]:
array8 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
array9 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(array9)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# Create 2D Array by using the zeros functions
array10 = np.zeros((3,4))
print(array10)
print("-"*20)
# Create 3D array by using the zeros functions
array11 = np.zeros((3,4,5))
print(array11)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
array11 = np.ones((3,5))
print(array11)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
array12 = np.ones((2,3,4))
print(array12)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [3]:
array13 = np.full((2,2),5)
print(array13)

[[5 5]
 [5 5]]


In [ ]:
# 2D Random Array
array14 = np.floor(np.random.rand(2,2) * 10)
print(array14)
print("-"*20)
# 3D Random Array
array15 = np.floor(np.random.rand(2,2,2) * 10)
print(array15)

[[2. 8.]
 [0. 8.]]
--------------------
[[[2. 5.]
  [5. 3.]]

 [[7. 2.]
  [7. 9.]]]


In [6]:
array16 = np.array([2,4,9])
print(array16.dtype) # Gives Data type of particular object

int64


In [7]:
int_array = np.array([-3,-1,0,1])
float_array = np.array([0.1,0.2,0.3])
complex_array = np.array([1+2j,2+3j,3+4j])
print(int_array.dtype)
print(float_array.dtype)
print(complex_array.dtype)

int64
float64
complex128


In [8]:
array17 = np.array([1,3,7], dtype='int32')
print(array1,array1.dtype)

[1 2 3 4 5] int64


In [ ]:
int_array1 = np.array([1,2,3], dtype='int8')
int_array2 = np.array([5,6,7], dtype='int16')
float_array = np.array([0.1,0.2,0.3], dtype='float32')
complex_array = np.array([1+2j,2+3j,3+4j], dtype='complex64')
print(int_array1.dtype)
print(int_array2.dtype)
print(float_array.dtype)
print(complex_array.dtype)

In [9]:
int_array = np.array([1,3,5,7])
# convert data type of int_array to float
float_array = int_array.astype('float64')
# print the arrays and their data types
print(int_array, int_array.dtype)
print(float_array, float_array.dtype)

[1 3 5 7] int64
[1. 3. 5. 7.] float64


In [15]:
array18 = np.arange(1,10)
print(array18.ndim)
array19= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array19.ndim)

1
3
