<a href="https://colab.research.google.com/github/mirajsankdecha/python/blob/main/Unit_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print(array1)

[1 2 3 4 5]


In [2]:
list2 = [6,7,8,9,10]
array2 = np.array(list2)
print(array2)

[ 6  7  8  9 10]


In [ ]:
array3 = np.zeros(4)
print(array3)

In [3]:
array4 = np.arange(10)
print(array4)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
array5 = np.arange(1,9,2)
print(array5)

[1 3 5 7]


In [13]:
array6 = np.floor(np.random.rand(5) * 10)
print(array6)

[0. 3. 0. 2. 6.]


In [11]:
array7 = np.empty(4)
print(array7)

[4.75194631e-310 0.00000000e+000 7.42861821e-091 9.15508060e-071]


In [15]:
array8 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
array9 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(array9)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# Create 2D Array by using the zeros functions
array10 = np.zeros((3,4))
print(array10)
# Create 3D array by using the zeros functions
array11 = np .zeros((3,4,5))
print(array11)